language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

dist: focal
sudo: required

# Requiring XCode 12, macOS 10.15
osx_image: xcode12

# TODO: add sanitizer & coverage builds
# TODO: add support for bionic builds

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update ;
      brew upgrade cmake ;
    fi

script:
  - mkdir -p ../build
  - cd ../build
  - bash $TRAVIS_BUILD_DIR/etc/TravisBuild.sh
