name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Initialize and update git submodules
      run: git submodule init && git submodule update

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} buildscript

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j2

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: src/IncrementalMonkey-build/bin/incmonktests.libincmonk.unit
